name: Build dockerfiles
# This workflow is triggered on pushes to the repository.
on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:    
      - master         # Push events on master branch

jobs:
  build:
    # Job name is Greeting
    name: Greeting
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: '1.9.3'
      - uses: actions/checkout@master
      - run: docker login -u dylanturn -p ${{ secrets.dockerhub_password }}
      - run: make executor-image
      - run: docker tag argoexec:latest dylanturn/argoexec:latest
      - run: docker push dylanturn/argoexec:latest
