name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
      
    - uses: actions/setup-go@v1
      with:
        go-version: '1.9.3'
          
    - name: Build the executor binaries
      run: make executor
      
    - name: Build the executor base image
      run: docker build -t argoexec-base --target argoexec-base .
      
    - name: Build the executor image
      run: docker build -t $(IMAGE_PREFIX)argoexec:$(IMAGE_TAG) --target argoexec .
